name: Transit Workflow
# Workflow trigger
on:
  pull_request:
    branches:
      - main
      - feature
jobs:
  tf_pre-commit:
    name: Terraform Pre-commit
    if: ${{ github.event_name == 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature') }}
    uses: saransh-10/terraform-cicd/.github/workflows/pre-commit_template.yml@main
