name: Terraform CI/CD Pipeline
on:
 workflow_call:
jobs:
  pre-commit:
    name: Pre-commit Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Trivy Vulnerability Scanner
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
                | sh -s -- -b ${{ vars.INSTALLPREFIX }} ${{ vars.TRIVYVERSION }}
      - name: Verify Trivy Installation
        run: trivy --version
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Install Terraform Docs
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/${{ vars.TFDOCSVERSION }}/terraform-docs-${{ vars.TFDOCSVERSION }}-$(uname)-amd64.tar.gz
              tar -xzf terraform-docs.tar.gz
              chmod +x terraform-docs
              sudo mv terraform-docs ${{ vars.INSTALLPREFIX }}/terraform-docs
      - name: Install Packer version
        run: |
          curl -sSLo ./packer.zip https://releases.hashicorp.com/packer/${{ vars.PACKERVERSION }}/packer_${{ vars.PACKERVERSION }}_linux_amd64.zip
          unzip packer.zip && mkdir -p ${{ vars.PACKERVERSION }} && mv packer ${{ vars.PACKERVERSION }} && chmod 755 ${{ vars.PACKERVERSION }}/packer
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install pre-commit
        run: python -m pip install -r requirements.txt
      - name: Run pre-commit checks
        run: pre-commit run --all-files
