name: Base Terraform Apply Template
on:
  workflow_call:
    secrets:
      Azure_Credential:
        required: true
    inputs:
      environment:
        required: true
        type: string
      var_file:
        required: true
        type: string
jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      # Checkout the repository
      - name: Checkout
        uses: "actions/checkout@v4"
      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{ github.workspace }}
      # Authenticate to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.Azure_Credential }}
      - name: Set up Azure environment variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
      # Terraform Initialise
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=Kartikeya-it-infra" \
            -backend-config="storage_account_name=oricademoaccount" \
            -backend-config="container_name=demo" \
            -backend-config="key=${{ inputs.backend }}.tfstate"
        working-directory: ${{ github.workspace }}/Workload
      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=${{ github.workspace }}/Deployment/${{ inputs.var_file }}
        working-directory: ${{ github.workspace }}/Workload
