name: Base Terraform Plan Template

on:
  workflow_dispatch: 
  workflow_call:
    secrets:
      Azure_Credential:
        required: true
      ARM_SECRET:
        required: true

    inputs:
      environment:
        required: true
        type: string

      var_file:
        required: true
        type: string
      

jobs:
  terraform-plan:
    name: Terraform Plan "${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment}}

    steps:
      # Checkout the repository
      - name: Checkout
        uses: "actions/checkout@v4"

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # # Authenticate to Azure
      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.ARM_SECRET }}
          
      - name: Terraform init azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.ARM_SECRET }}
          resource_group_name: Orica-RG
          container_name: tfstate
          storage_account_name: oricatest3
          file_name: terraform1.tfstate
          tf_working_directory: ${{ github.workspace }}/Workload

      # Generate the execution plan for Terraform
      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes

      - name: Terraform Plan
        run: terraform plan -out=terraform.tfplan -var-file=${{ github.workspace }}/Deployment/${{ inputs.var_file }}
        working-directory: ${{ github.workspace }}/Workload

      # Save plan to artifacts
      - name: Upload Terraform Plan
        id: upload_plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ github.workspace }}
